In [1]:
import torch
import torch.nn as nn
from torch.nn import TransformerEncoderLayer, TransformerEncoder

In [2]:
bag_of_CLS = torch.rand(16, 10, 768) # [seq_len, batch_size, d_model]
type_mask = torch.tensor([[1],
                          [2],
                          [2],
                          [2],
                          [2],
                          [2],
                          [2],
                          [2],
                          [2],
                          [0],
                          [0],
                          [0],
                          [0],
                          [0],
                          [0],
                          [0]]) # [seq_len, batch_size]
# type_mask = None

In [22]:
class MUTANT(nn.Module):

    def __init__(self, d_model=768, seq_len=16, dropout=0.1):
        super(MUTANT,self).__init__()
        self.seq_len = seq_len
        self.dropout = nn.Dropout(p=dropout)
        self.token_type_embeddings = nn.Embedding(3, d_model)
        encoder_layer = nn.TransformerEncoderLayer(d_model=d_model, nhead=2)
        self.transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=2)
        self.linear_head_0 = nn.Linear(d_model, 1)
        self.linear_head_1 = nn.Linear(d_model, 1)
        self.linear_head_2 = nn.Linear(d_model, 1)
        self.linear_head_3 = nn.Linear(d_model, 1)
        self.linear_head_4 = nn.Linear(d_model, 1)
        self.linear_head_5 = nn.Linear(d_model, 1)
        self.linear_head_6 = nn.Linear(d_model, 1)
        self.linear_head_7 = nn.Linear(d_model, 1)
        self.linear_head_8 = nn.Linear(d_model, 1)
        self.linear_head_9 = nn.Linear(d_model, 1)
        self.linear_head_10 = nn.Linear(d_model, 1)
        self.linear_head_11 = nn.Linear(d_model, 1)
        self.linear_head_12 = nn.Linear(d_model, 1)
        self.linear_head_13 = nn.Linear(d_model, 1)
        self.linear_head_14 = nn.Linear(d_model, 1)
        self.linear_head_15 = nn.Linear(d_model, 1)

                
    def forward_embed(self, input_CLSs, type_mask=None):
        # input_CLSs -> [seq_len, batch_size, d_model]
        # type_mask -> [seq_len, batch_size] 0 or 1 for different types
        input_CLSs_shape = input_CLSs.shape
        
        if isinstance(type_mask, torch.Tensor):
            token_type_embeddings = self.token_type_embeddings(type_mask)
            input_CLSs = input_CLSs + token_type_embeddings
            
        output_CLSs = self.transformer_encoder(input_CLSs)
        return output_CLSs
    
    
    def forward(self, input_CLSs, type_mask=None):
        # input_CLSs -> [seq_len, batch_size, d_model]
        # type_mask -> [seq_len, batch_size] 0 or 1 for different types
        seq_length = input_CLSs.shape[0]
        
        if isinstance(type_mask, torch.Tensor):
            token_type_embeddings = self.token_type_embeddings(type_mask)
            input_CLSs = input_CLSs + token_type_embeddings
            
        output_CLSs = self.transformer_encoder(input_CLSs)
        
        output_linear = []
        output_linear.append(self.linear_head_0(output_CLSs[0,:])) 
        output_linear.append(self.linear_head_1(output_CLSs[1,:])) 
        output_linear.append(self.linear_head_2(output_CLSs[2,:])) 
        output_linear.append(self.linear_head_3(output_CLSs[3,:])) 
        output_linear.append(self.linear_head_4(output_CLSs[4,:])) 
        output_linear.append(self.linear_head_5(output_CLSs[5,:])) 
        output_linear.append(self.linear_head_6(output_CLSs[6,:])) 
        output_linear.append(self.linear_head_7(output_CLSs[7,:])) 
        output_linear.append(self.linear_head_8(output_CLSs[8,:])) 
        output_linear.append(self.linear_head_9(output_CLSs[9,:])) 
        output_linear.append(self.linear_head_10(output_CLSs[10,:])) 
        output_linear.append(self.linear_head_11(output_CLSs[11,:])) 
        output_linear.append(self.linear_head_12(output_CLSs[12,:])) 
        output_linear.append(self.linear_head_13(output_CLSs[13,:])) 
        output_linear.append(self.linear_head_14(output_CLSs[14,:])) 
        output_linear.append(self.linear_head_15(output_CLSs[15,:])) 
        
        return output_linear
    
    def get_device(self):
        return next(self.parameters()).device

In [23]:
model = MUTANT(d_model=768)

In [24]:
output_linear = model.forward(bag_of_CLS, type_mask)

In [25]:
output_linear

[tensor([[-0.8624],
         [-0.9680],
         [-1.1681],
         [-0.8198],
         [-0.9140],
         [-0.8340],
         [-0.9086],
         [-0.7976],
         [-0.8178],
         [-0.8323]], grad_fn=<AddmmBackward>),
 tensor([[0.7405],
         [0.7269],
         [0.9635],
         [0.6967],
         [0.9628],
         [0.9827],
         [0.5174],
         [0.5015],
         [0.5148],
         [0.2752]], grad_fn=<AddmmBackward>),
 tensor([[-0.9871],
         [-1.2576],
         [-0.5691],
         [-0.8490],
         [-0.8600],
         [-0.9272],
         [-0.9332],
         [-1.0164],
         [-1.1563],
         [-1.0470]], grad_fn=<AddmmBackward>),
 tensor([[0.1465],
         [0.1904],
         [0.5416],
         [0.3328],
         [0.1358],
         [0.4842],
         [0.4220],
         [0.4988],
         [0.2499],
         [0.2484]], grad_fn=<AddmmBackward>),
 tensor([[-0.2280],
         [-0.7589],
         [-0.9218],
         [-0.5936],
         [-0.6172],
         [-0

In [26]:
model.state_dict()

OrderedDict([('token_type_embeddings.weight',
              tensor([[ 0.1166, -1.3008,  0.2340,  ..., -0.2521,  0.7791, -0.0816],
                      [ 1.6010, -0.1963, -0.5918,  ...,  0.2882,  0.1526, -0.0637],
                      [ 0.5112, -0.0791,  0.8217,  ..., -1.3118, -1.2126, -0.8178]])),
             ('transformer_encoder.layers.0.self_attn.in_proj_weight',
              tensor([[ 0.0048,  0.0266,  0.0261,  ..., -0.0142, -0.0331, -0.0367],
                      [-0.0091, -0.0102,  0.0121,  ..., -0.0257, -0.0269, -0.0036],
                      [ 0.0079,  0.0349,  0.0440,  ..., -0.0156, -0.0351,  0.0172],
                      ...,
                      [-0.0089,  0.0198,  0.0248,  ...,  0.0347, -0.0318, -0.0089],
                      [-0.0331,  0.0415,  0.0396,  ..., -0.0038,  0.0375,  0.0408],
                      [-0.0116, -0.0337, -0.0429,  ...,  0.0440, -0.0243, -0.0121]])),
             ('transformer_encoder.layers.0.self_attn.in_proj_bias',
              tensor([0.,